"""
Compression — RAW → MOD → MAX tier promotion + scene-level compression.

Three compressors:
  ArcCompressor     — per-agent. Triggers on snap threshold (emotional
                      phase transition). Generates MOD-tier arc summaries.
  SceneCompressor   — group-level. Triggers on significant presence changes
                      (NPCs entering/exiting the scene). Generates compact
                      SVO scene-break markers in the group memory timeline.
  EssenceDistiller  — operational. Compacts old MOD → MAX when point count
                      impacts performance.

See living doc §Memory Architecture, §Storage Trigger, and Phase 2 plan.
"""
from __future__ import annotations

import logging
import re
from typing import Any, Optional, TYPE_CHECKING

from qdrant_client.models import FieldCondition, Filter, MatchValue, Range

from shared.constants import COLLECTION_NPC_MEMORIES

from .memory_writer import MemoryWriter
from .qdrant_client import get_points_by_ids, scroll_filtered

if TYPE_CHECKING:
    from .event_accumulator import PresenceChanges, TieredMemory

logger = logging.getLogger(__name__)

# Matches capitalized multi-char words (names, places)
_ENTITY_RE = re.compile(r"\b[A-Z][a-zA-Z]{2,}\b")

# Snap threshold for arc boundary detection.
# Tunable per-agent via harmonic_buffer personality parameters.
DEFAULT_SNAP_THRESHOLD = 0.3


class ArcCompressor:
    """
    Generates MOD-tier arc summaries from spans of RAW events.

    An arc is the emotional span between two snap threshold crossings.
    The summary captures: what happened, who was involved, how it felt,
    and what changed. It points back to the RAW point IDs for expansion.

    The summary text is generated by the LLM (or a lightweight
    summarization heuristic when the LLM is busy).
    """

    def __init__(
        self,
        writer: MemoryWriter,
        llm_summarize_fn: Optional[Any] = None,
    ):
        """
        Args:
            writer: Memory writer for MOD/MAX writes.
            llm_summarize_fn: Async callable(text: str) -> str that
                summarizes text. If None, uses heuristic truncation.
        """
        self._writer = writer
        self._llm_summarize = llm_summarize_fn

    def should_generate_arc(self, snap: float, threshold: float = DEFAULT_SNAP_THRESHOLD) -> bool:
        """Check if snap exceeds threshold (event boundary detected)."""
        return abs(snap) >= threshold

    async def generate_arc_summary(
        self,
        agent_id: str,
        arc_start_ts: float,
        arc_end_ts: float,
        semantic_vector: list[float],
        emotional_vector: list[float],
        game_ts: float,
        location: Optional[str] = None,
    ) -> Optional[str]:
        """
        Generate a MOD-tier arc summary from RAW points in the time window.

        Retrieves all RAW points for this agent between arc_start_ts and
        arc_end_ts, summarizes them, and writes the summary to Qdrant.

        Returns the arc summary point ID, or None if no RAW points found.
        """
        # Retrieve RAW points in the arc window
        arc_filter = Filter(
            must=[
                FieldCondition(key="agent_id", match=MatchValue(value=agent_id)),
                FieldCondition(key="tier", match=MatchValue(value="RAW")),
                FieldCondition(key="game_ts", range=Range(gte=arc_start_ts, lte=arc_end_ts)),
            ]
        )
        raw_points = await scroll_filtered(
            collection=COLLECTION_NPC_MEMORIES,
            scroll_filter=arc_filter,
            limit=200,
            order_by="game_ts",
        )

        if not raw_points:
            logger.debug(
                "No RAW points for arc [%.2f, %.2f] agent=%s",
                arc_start_ts, arc_end_ts, agent_id,
            )
            return None

        # Extract content for summarization
        raw_texts = [p["payload"].get("content", "") for p in raw_points]
        raw_ids = [p["id"] for p in raw_points]

        # Generate summary text
        combined_text = "\n".join(raw_texts)
        summary_text = self._summarize(combined_text, agent_id)

        # Write the arc summary
        point_id = await self._writer.write_arc_summary(
            agent_id=agent_id,
            summary_text=summary_text,
            semantic_vector=semantic_vector,
            emotional_vector=emotional_vector,
            arc_start_ts=arc_start_ts,
            arc_end_ts=arc_end_ts,
            raw_point_ids=raw_ids,
            game_ts=game_ts,
            location=location,
        )

        logger.info(
            "Arc summary generated: agent=%s arc=[%.2f, %.2f] %d RAW points → %s",
            agent_id, arc_start_ts, arc_end_ts, len(raw_ids), point_id,
        )
        return point_id

    def _summarize(self, text: str, agent_id: str) -> str:
        """
        Summarize text using LLM or heuristic fallback.

        The LLM path uses a short system prompt requesting a concise
        summary of the events, preserving emotional tone and key actions.
        """
        if self._llm_summarize is not None:
            try:
                return self._llm_summarize(text)
            except Exception as exc:
                logger.warning(
                    "LLM summarization failed for %s, using heuristic: %s",
                    agent_id, exc,
                )
        # Heuristic fallback: first and last sentences, truncated
        return self._heuristic_summarize(text)

    @staticmethod
    def _heuristic_summarize(text: str, max_chars: int = 500) -> str:
        """
        Simple heuristic summarization — first and last segments.

        Not great, but better than nothing when the LLM is busy.
        """
        lines = [ln.strip() for ln in text.split("\n") if ln.strip()]
        if not lines:
            return ""
        if len(lines) <= 3:
            return " ".join(lines)[:max_chars]
        # First line + "..." + last two lines
        summary = f"{lines[0]} [...] {lines[-2]} {lines[-1]}"
        return summary[:max_chars]


class SceneCompressor:
    """Generates scene-break markers when the group composition changes.

    Triggered by significant presence changes (2+ NPCs entering/exiting).
    Produces compact SVO-form summaries of the preceding scene and inserts
    them into the group memory's compressed tier.

    Scene markers serve as retrieval anchors: compact enough for the
    keywords tier (~15 tokens), rich enough to trigger recognition
    when a similar scene recurs.

    Not per-agent — this compresses the shared group timeline.
    """

    # Minimum total enter+exit count to consider a scene boundary.
    # 1 NPC arriving is routine; 2+ is a meaningful composition shift.
    MIN_CHANGES: int = 2

    def should_compress(
        self,
        presence_changes: "PresenceChanges",
    ) -> bool:
        """Check if presence changes warrant a scene-break marker."""
        total = len(presence_changes.entered) + len(presence_changes.exited)
        return total >= self.MIN_CHANGES

    def compress_scene(
        self,
        group_memory: "TieredMemory",
        location: str,
        presence_changes: "PresenceChanges",
    ) -> str:
        """Generate a scene-break marker and insert into group memory.

        Extracts participants and key actions from recent verbatim entries,
        combines with location and presence delta into an SVO-form marker:
          [Scene: Whiterun] Lydia, Player | discussed dragons | Belethor exited

        The marker goes into group_memory.compressed (MOD tier equivalent
        for the group timeline). The slide_window pipeline will eventually
        distill it further into keywords.

        Returns the marker text.
        """
        # Extract participants from recent verbatim (who spoke)
        speakers = _extract_speakers(group_memory.verbatim[-10:])

        # Extract key entities/actions from recent content
        action_summary = _extract_action_summary(group_memory.verbatim[-10:])

        # Build the marker
        parts = [f"[Scene: {location}]"]

        if speakers:
            parts.append(", ".join(speakers))

        if action_summary:
            parts.append(action_summary)

        if presence_changes.entered:
            parts.append(f"+{','.join(presence_changes.entered)}")
        if presence_changes.exited:
            parts.append(f"-{','.join(presence_changes.exited)}")

        marker = " | ".join(parts)

        # Insert into the compressed tier of group memory
        group_memory.compressed.append(marker)

        logger.info(
            "Scene break: %s (%d entered, %d exited)",
            marker[:80],
            len(presence_changes.entered),
            len(presence_changes.exited),
        )
        return marker


def _extract_speakers(verbatim: list[dict]) -> list[str]:
    """Extract unique speaker names from verbatim entries, preserving order."""
    seen: set[str] = set()
    speakers: list[str] = []
    for entry in verbatim:
        role = entry.get("role", "")
        if role and role not in seen:
            seen.add(role)
            speakers.append(role)
    return speakers


def _extract_action_summary(verbatim: list[dict], max_chars: int = 60) -> str:
    """Extract a compact action summary from recent verbatim entries.

    Heuristic SVO extraction: finds named entities and action-like verbs
    from the content of recent entries. Produces a brief phrase.
    """
    if not verbatim:
        return ""

    # Collect all content text
    all_text = " ".join(entry.get("content", "") for entry in verbatim)
    if not all_text.strip():
        return ""

    # Extract named entities (capitalized words)
    entities = list(dict.fromkeys(_ENTITY_RE.findall(all_text)))  # unique, ordered

    # Take the first sentence of the most recent entry as the action core
    last_content = verbatim[-1].get("content", "")
    # First clause: up to first punctuation or 60 chars
    clause_match = re.match(r"^(.+?)[.!?,;]", last_content)
    if clause_match:
        action_core = clause_match.group(1).strip()
    else:
        action_core = last_content[:max_chars].strip()

    # Combine: entities mentioned + action core, capped
    entity_str = ",".join(entities[:3])  # Top 3 entities
    if entity_str and action_core:
        result = f"{action_core} re:{entity_str}"
    elif action_core:
        result = action_core
    elif entity_str:
        result = f"re:{entity_str}"
    else:
        result = ""

    return result[:max_chars]


class EssenceDistiller:
    """
    Generates MAX-tier compressed essences from groups of MOD arc summaries.

    Operational compaction — triggered when RAW/MOD point count impacts
    query performance. Groups related arcs (same agent, same location,
    similar emotional signature) and distills into a single essence.

    This is Phase 3 work — thin implementation for now.
    """

    def __init__(
        self,
        writer: MemoryWriter,
        llm_summarize_fn: Optional[Any] = None,
    ):
        self._writer = writer
        self._llm_summarize = llm_summarize_fn

    async def distill_arcs(
        self,
        agent_id: str,
        arc_point_ids: list[str],
        semantic_vector: list[float],
        emotional_vector: list[float],
        game_ts: float,
    ) -> Optional[str]:
        """
        Distill multiple arc summaries into a single MAX essence.

        Returns the essence point ID, or None if no arcs found.
        """
        arc_points = await get_points_by_ids(
            COLLECTION_NPC_MEMORIES, arc_point_ids
        )
        if not arc_points:
            return None

        arc_texts = [p["payload"].get("content", "") for p in arc_points]
        combined = "\n".join(arc_texts)

        # Distill
        if self._llm_summarize:
            try:
                essence_text = self._llm_summarize(combined)
            except Exception:
                essence_text = ArcCompressor._heuristic_summarize(combined, max_chars=300)
        else:
            essence_text = ArcCompressor._heuristic_summarize(combined, max_chars=300)

        point_id = await self._writer.write_compressed_essence(
            agent_id=agent_id,
            essence_text=essence_text,
            semantic_vector=semantic_vector,
            emotional_vector=emotional_vector,
            source_arc_ids=arc_point_ids,
            game_ts=game_ts,
        )

        logger.info(
            "Essence distilled: agent=%s from %d arcs → %s",
            agent_id, len(arc_point_ids), point_id,
        )
        return point_id
