"""
Compression — RAW → MOD → MAX tier promotion.

Arc summaries (MOD) are generated when snap exceeds threshold — an event
boundary has been detected, meaning the emotional trajectory changed.
The summary condenses the span from arc-start to arc-end into a search aid.

Essence distillation (MAX) is operational compaction when point count
impacts performance. Not part of the core cognitive loop.

LLM is used for summarization — the same Ollama instance used for NPC
dialogue. Compression prompts are short and simple.

See living doc §Memory Architecture and §Storage Trigger.
"""
from __future__ import annotations

import logging
from typing import Any, Optional

from qdrant_client.models import FieldCondition, Filter, MatchValue, Range

from shared.constants import COLLECTION_NPC_MEMORIES

from .memory_writer import MemoryWriter
from .qdrant_client import get_points_by_ids, scroll_filtered

logger = logging.getLogger(__name__)

# Snap threshold for arc boundary detection.
# Tunable per-agent via harmonic_buffer personality parameters.
DEFAULT_SNAP_THRESHOLD = 0.3


class ArcCompressor:
    """
    Generates MOD-tier arc summaries from spans of RAW events.

    An arc is the emotional span between two snap threshold crossings.
    The summary captures: what happened, who was involved, how it felt,
    and what changed. It points back to the RAW point IDs for expansion.

    The summary text is generated by the LLM (or a lightweight
    summarization heuristic when the LLM is busy).
    """

    def __init__(
        self,
        writer: MemoryWriter,
        llm_summarize_fn: Optional[Any] = None,
    ):
        """
        Args:
            writer: Memory writer for MOD/MAX writes.
            llm_summarize_fn: Async callable(text: str) -> str that
                summarizes text. If None, uses heuristic truncation.
        """
        self._writer = writer
        self._llm_summarize = llm_summarize_fn

    def should_generate_arc(self, snap: float, threshold: float = DEFAULT_SNAP_THRESHOLD) -> bool:
        """Check if snap exceeds threshold (event boundary detected)."""
        return abs(snap) >= threshold

    async def generate_arc_summary(
        self,
        agent_id: str,
        arc_start_ts: float,
        arc_end_ts: float,
        semantic_vector: list[float],
        emotional_vector: list[float],
        game_ts: float,
        location: Optional[str] = None,
    ) -> Optional[str]:
        """
        Generate a MOD-tier arc summary from RAW points in the time window.

        Retrieves all RAW points for this agent between arc_start_ts and
        arc_end_ts, summarizes them, and writes the summary to Qdrant.

        Returns the arc summary point ID, or None if no RAW points found.
        """
        # Retrieve RAW points in the arc window
        arc_filter = Filter(
            must=[
                FieldCondition(key="agent_id", match=MatchValue(value=agent_id)),
                FieldCondition(key="tier", match=MatchValue(value="RAW")),
                FieldCondition(key="game_ts", range=Range(gte=arc_start_ts, lte=arc_end_ts)),
            ]
        )
        raw_points = await scroll_filtered(
            collection=COLLECTION_NPC_MEMORIES,
            scroll_filter=arc_filter,
            limit=200,
            order_by="game_ts",
        )

        if not raw_points:
            logger.debug(
                "No RAW points for arc [%.2f, %.2f] agent=%s",
                arc_start_ts, arc_end_ts, agent_id,
            )
            return None

        # Extract content for summarization
        raw_texts = [p["payload"].get("content", "") for p in raw_points]
        raw_ids = [p["id"] for p in raw_points]

        # Generate summary text
        combined_text = "\n".join(raw_texts)
        summary_text = self._summarize(combined_text, agent_id)

        # Write the arc summary
        point_id = await self._writer.write_arc_summary(
            agent_id=agent_id,
            summary_text=summary_text,
            semantic_vector=semantic_vector,
            emotional_vector=emotional_vector,
            arc_start_ts=arc_start_ts,
            arc_end_ts=arc_end_ts,
            raw_point_ids=raw_ids,
            game_ts=game_ts,
            location=location,
        )

        logger.info(
            "Arc summary generated: agent=%s arc=[%.2f, %.2f] %d RAW points → %s",
            agent_id, arc_start_ts, arc_end_ts, len(raw_ids), point_id,
        )
        return point_id

    def _summarize(self, text: str, agent_id: str) -> str:
        """
        Summarize text using LLM or heuristic fallback.

        The LLM path uses a short system prompt requesting a concise
        summary of the events, preserving emotional tone and key actions.
        """
        if self._llm_summarize is not None:
            try:
                return self._llm_summarize(text)
            except Exception as exc:
                logger.warning(
                    "LLM summarization failed for %s, using heuristic: %s",
                    agent_id, exc,
                )
        # Heuristic fallback: first and last sentences, truncated
        return self._heuristic_summarize(text)

    @staticmethod
    def _heuristic_summarize(text: str, max_chars: int = 500) -> str:
        """
        Simple heuristic summarization — first and last segments.

        Not great, but better than nothing when the LLM is busy.
        """
        lines = [ln.strip() for ln in text.split("\n") if ln.strip()]
        if not lines:
            return ""
        if len(lines) <= 3:
            return " ".join(lines)[:max_chars]
        # First line + "..." + last two lines
        summary = f"{lines[0]} [...] {lines[-2]} {lines[-1]}"
        return summary[:max_chars]


class EssenceDistiller:
    """
    Generates MAX-tier compressed essences from groups of MOD arc summaries.

    Operational compaction — triggered when RAW/MOD point count impacts
    query performance. Groups related arcs (same agent, same location,
    similar emotional signature) and distills into a single essence.

    This is Phase 3 work — thin implementation for now.
    """

    def __init__(
        self,
        writer: MemoryWriter,
        llm_summarize_fn: Optional[Any] = None,
    ):
        self._writer = writer
        self._llm_summarize = llm_summarize_fn

    async def distill_arcs(
        self,
        agent_id: str,
        arc_point_ids: list[str],
        semantic_vector: list[float],
        emotional_vector: list[float],
        game_ts: float,
    ) -> Optional[str]:
        """
        Distill multiple arc summaries into a single MAX essence.

        Returns the essence point ID, or None if no arcs found.
        """
        arc_points = await get_points_by_ids(
            COLLECTION_NPC_MEMORIES, arc_point_ids
        )
        if not arc_points:
            return None

        arc_texts = [p["payload"].get("content", "") for p in arc_points]
        combined = "\n".join(arc_texts)

        # Distill
        if self._llm_summarize:
            try:
                essence_text = self._llm_summarize(combined)
            except Exception:
                essence_text = ArcCompressor._heuristic_summarize(combined, max_chars=300)
        else:
            essence_text = ArcCompressor._heuristic_summarize(combined, max_chars=300)

        point_id = await self._writer.write_compressed_essence(
            agent_id=agent_id,
            essence_text=essence_text,
            semantic_vector=semantic_vector,
            emotional_vector=emotional_vector,
            source_arc_ids=arc_point_ids,
            game_ts=game_ts,
        )

        logger.info(
            "Essence distilled: agent=%s from %d arcs → %s",
            agent_id, len(arc_point_ids), point_id,
        )
        return point_id
